### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nanoxd** [kumabook/MusicFav#4]
Hey! I stumbled across your repo while looking for usage of ReactiveCocoa 3 on GitHub. I had a few questions for you, if you wouldn't mind answering them.
- How do you feel about running both Carthage and CocoaPods? Do you notice any issues? 
- What are main pain points with RAC 3? How did you overcome them? 
- In what capacity does RAC interface with Realm in this project?
- Would you do anything differently if starting today?

Thanks
![high-five](https://cloud.githubusercontent.com/assets/1889575/7441771/0b8204a0-f0ab-11e4-82bd-00b64e521aea.gif)

**Comment by kumabook** [comment]
Hi!  thank you for interest and sorry for the delay in responding

> How do you feel about running both Carthage and CocoaPods? Do you notice any issues? 

It's almost alright.
But, some Carthage library need to be fixed xcode project settings ( such as target sdk).
And carthage caches git repository. If you need to cutomize the library, you must clear cache `rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/xxx`

> What are main pain points with RAC 3? How did you overcome them? 

There isn't enough document. I used RAC3 unittests as referenced.

> In what capacity does RAC interface with Realm in this project?

I defined both Model and Persistent class, Persistent is a just DAO(with realm)
And model classes and Loader class have Signal instances as instance variable and class variable.
The signal produce event enum (Created, Removed ...)
ViewController and view classes observe them. 

> Would you do anything differently if starting today?

When I started to use RAC3, it is under developing, so There are big difference in some class name and  method signature.
I want to change some class name, for example: Playlist.Event, because ReactiveCocoaEvent also exists. But almost ok.

I hope to reference.
